Feature/cplp 483 admin registration requests Page and unit tests for page
catenax-ng/product-portal-frontend pull request #10
Opened 2022-04-05 17:07 UTC by fatihayyildiz

RegistrationRequests page header implemented
RegistrationRequests page navigation implemented to user menu
Redux store usage some alignment for page unit tests
Unit test and integration tests implemented for RegistrationRequests page

**Table Shared Component Changes**
Number of columns property removed. Component itself counts rows and set number at title
Toolbar Search icon and Filter icon colours are changed based with design

2022-04-05 17:09 UTC, fatihayyildiz commented
@oyo There is some changes to be able to activate unit test for page. I tried to put some comments as much as I can. We can take a detail look together if you want :)

2022-04-05 17:10 UTC, fatihayyildiz commented
@christianraysono I made small changes for Table component. Could you please take a look :) ?

2022-04-06 11:08 UTC, christianraysono approved these changes
Table looks good

2022-04-06 11:08 UTC, christianraysono commented on cx-portal-shared-components/src/components/basic/Table/components/Toolbar/index.tsx
> +              ({rowCount})
Thanks for renaming!

2022-04-06 12:30 UTC, DianaRenz approved these changes

2022-04-07 07:15 UTC, floriansommerraysono approved these changes

2022-04-07 08:40 UTC, oyo requested changes
i am getting a lot of errors/warnings trying to build the library on this branch:

(!) Plugin typescript: @rollup/plugin-typescript TS2582: Cannot find name 'describe'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha`.
src/components/basic/Table/components/Toolbar/helper.test.ts: (23:1)

23 describe('TableToolbarTest', () => {
   ~~~~~~~~

2022-04-07 09:09 UTC, oyo approved these changes
added commit to get rid of the error messages - now approved :)

2022-04-08 14:18 UTC, fatihayyildiz commented
Merge conflict resolved. I am merging to main branch

2022-04-08 14:18 UTC, merged