Feature/cplp 658 header component
catenax-ng/product-portal-frontend pull request #110
Opened 2022-06-09 11:06 UTC by PI-FerasAhmad

- Main navigation component added
- Main header component added
- Page header component expanded
- Header and navigation component implemented in Portal

2022-06-13 13:17 UTC, fatihayyildiz commented
I started to checking changes

2022-06-13 13:54 UTC, fatihayyildiz requested changes

2022-06-13 13:54 UTC, fatihayyildiz commented on cx-portal-shared-components/src/components/basic/Headers/MainHeader/Components/MainHeaderTitle.tsx
> +        <Typography
Could we use our Typography component here ?

2022-06-14 07:16 UTC, floriansommerraysono commented on cx-portal-shared-components/src/components/basic/Headers/MainHeader/Components/MainHeaderTitle.tsx
> +        <Typography
I'll change it

2022-06-14 07:38 UTC, floriansommerraysono commented on cx-portal/src/components/pages/UserManagement/UserDetails/index.tsx
> -            // {
This should not be removed because needed in the future. But wasn't commented. I'll add one now.

2022-06-14 07:57 UTC, floriansommerraysono approved these changes

2022-06-14 14:30 UTC, fatihayyildiz commented on cx-portal-shared-components/src/components/basic/Headers/MainHeader/Components/MainHeaderTitle.tsx
> +        <Typography
Looks nice, thanks Florian

2022-06-14 22:23 UTC, merged