CPLP-616: Add validation for user overlay input fields
catenax-ng/product-portal-frontend pull request #15
Opened 2022-04-08 16:12 UTC by christianraysono

Adds useFormValidation hook
Implements validation for user overlay input fields
Renames tab state variables

2022-04-08 18:59 UTC, floriansommerraysono commented
Thanks for renaming tab state variables. I was not happy with the value-value. :-)

2022-04-08 18:59 UTC, floriansommerraysono approved these changes

2022-04-09 10:48 UTC, oyo requested changes
generally really good, but see my other comments

2022-04-09 10:48 UTC, oyo commented on cx-portal/src/components/pages/UserManagement/AddUserOverlay/SingleUserContent.tsx
> +  })
Do we really need the `required` attribute? We could specify that by giving a `pattern` that allows an empty string. Also I would prefer to combine that with the `userInputs` so we have all the configuration in one place like:
```
{
      key: 'firstname',
      label: t('global.field.first'),
      placeholder: t('global.field.first'),
      helperText: '',
      pattern: /^([A-Za-zÀ-ÿ-,.']{1,40}[ ]?){1,8}$/i,
},
```

2022-04-09 10:48 UTC, oyo commented on cx-portal/src/components/pages/UserManagement/AddUserOverlay/SingleUserContent.tsx
> +      pattern: /^.([A-Za-zÀ-ÿ-,.']{1,40}[ ]?){1,8}$/i,
why is that dot allowed as first character in `/^.(` ?

2022-04-09 10:48 UTC, oyo commented on cx-portal/src/components/pages/UserManagement/AddUserOverlay/SingleUserContent.tsx
> +      pattern: /^.([A-Za-zÀ-ÿ-,.']{1,40}[ ]?){1,8}$/i,
first char arbitrary

2022-04-11 10:16 UTC, christianraysono commented on cx-portal/src/components/pages/UserManagement/AddUserOverlay/SingleUserContent.tsx
> +  })
The validation hook is now refactored to use the `userInputs` array.

2022-04-11 10:16 UTC, christianraysono commented on cx-portal/src/components/pages/UserManagement/AddUserOverlay/SingleUserContent.tsx
> +      pattern: /^.([A-Za-zÀ-ÿ-,.']{1,40}[ ]?){1,8}$/i,
Pattern is fixed

2022-04-11 10:17 UTC, christianraysono commented on cx-portal/src/components/pages/UserManagement/AddUserOverlay/SingleUserContent.tsx
> +      pattern: /^.([A-Za-zÀ-ÿ-,.']{1,40}[ ]?){1,8}$/i,
Pattern is fixed

2022-04-11 13:27 UTC, oyo approved these changes
looks good now

2022-04-12 06:55 UTC, merged