Feature/cookies page/cplp 713
catenax-ng/product-portal-frontend pull request #16
Opened 2022-04-11 10:44 UTC by nidhigarg-bmw

Add cookie page with locals file

2022-04-11 11:38 UTC, oyo requested changes
some changes, see comments

2022-04-11 11:38 UTC, oyo commented on cx-portal/src/assets/locales/de/main.json
> +      "description1": "A cookie is a small piece of data (text file) that a website - when visited by a user - asks your browser to store on your device in order to remember information about you, su
should these texts be translated to german? Maybe you want to put that german part into the translator first:
https://portal-dev.demo.catena-x.net/translator

2022-04-11 11:38 UTC, oyo commented on cx-portal/src/assets/locales/en/main.json
> +      "description2_third": "Remember your prefernces and settings;",
typo: preferences

2022-04-11 11:41 UTC, jjeroch commented on cx-portal/src/assets/locales/de/main.json
> +      "description1": "A cookie is a small piece of data (text file) that a website - when visited by a user - asks your browser to store on your device in order to remember information about you, su
@oyo  quick info - Nidhi and I aligned that she doesn't need to translate. I will do the translation, she will take over the technical implementation.

2022-04-11 11:43 UTC, jjeroch commented
@oyo for me the question is more general. I would like to see the footer pages in a standalone translation file. Any other need from your side?

2022-04-11 11:49 UTC, oyo commented
> @oyo for me the question is more general. I would like to see the footer pages in a standalone translation file. Any other need from your side?

Currently we have two different i18n namespaces/files `main` and `help`
https://github.com/catenax-ng/product-portal-frontend/tree/main/cx-portal/src/assets/locales/en

Maybe we rename the `help.json` to `footer.json` and bundle all footer resources there. We could also have an own file for every page but that would result in a lot of small files.

2022-04-11 11:52 UTC, nidhigarg-bmw commented on cx-portal/src/assets/locales/en/main.json
> +      "description2_third": "Remember your prefernces and settings;",
@oyo So what typo I have to follow exactly ? 
description2-first or description2First

2022-04-11 11:52 UTC, jjeroch commented
@oyo yeah changing "help" to "footer" sounds actually good

2022-04-11 11:55 UTC, oyo commented
@jjeroch okay do you want to create a ticket for that or shall I do? maybe @nidhigarg-bmw could take that task?

2022-04-11 12:20 UTC, oyo commented on cx-portal/src/assets/locales/en/main.json
> +      "description2_third": "Remember your prefernces and settings;",
Line 191: missing `e`
` "description2_third": "Remember your preferences and settings;",`

2022-04-11 13:44 UTC, oyo approved these changes
would be nice if you could fix that typo

2022-04-11 20:19 UTC, jjeroch requested changes
Hi @nidhigarg-bmw  please add all the cookie and imprint translations into the "help" file and change the name from "help" to "Footer". Thanks"

2022-04-12 05:09 UTC, jjeroch approved these changes

2022-04-12 05:21 UTC, merged