fixed companyUserId issue
catenax-ng/product-portal-frontend pull request #162
Opened 2022-07-25 12:04 UTC by nidhigarg-bmw

2022-07-25 12:39 UTC, jjeroch requested changes

2022-07-25 12:39 UTC, jjeroch commented on cx-portal/src/components/pages/UserManagement/UserDetails/index.tsx
>              userDetailsCards={userDetailsToCards(ownUser)}
Quick Question on this @nidhigarg-bmw the function is mentioning "ownUser".
In this scenario we are displaying user details of an user under the same organization/company. Shall we really call it "ownUser"? I feel that might be confusing. What do you think?

2022-07-25 12:39 UTC, jjeroch commented on cx-portal/src/components/shared/basic/UserDetails/UserDetailCard.tsx
>  export type OwnUser = {
Can we change this from "OwnUser" to something like "UserDetails" without breaking the logic?

2022-07-26 07:46 UTC, nidhigarg-bmw commented on cx-portal/src/components/pages/UserManagement/UserDetails/index.tsx
>              userDetailsCards={userDetailsToCards(ownUser)}
@jjeroch Can you create new ticket for this? As there will be lots of changes if I am going to change this name. What you think ?

2022-07-26 20:39 UTC, jjeroch commented on cx-portal/src/components/pages/UserManagement/UserDetails/index.tsx
>              userDetailsCards={userDetailsToCards(ownUser)}
@nidhigarg-bmw can you quickly give me some context regarding the change size. Is the issue related to the initial developed component or what is triggering the bigger efforts of this change?

2022-07-27 11:23 UTC, oyo approved these changes
okay from my POV - refactoring should be a separate ticket because that is from older code

2022-07-27 11:23 UTC, oyo commented on cx-portal/src/components/pages/UserManagement/UserDetails/index.tsx
>              userDetailsCards={userDetailsToCards(ownUser)}
That code using `OwnUser` was there before the current PR - maybe it was me using the OwnUser object despite the inappropriate name. So I agree this should be a separate ticket to clean that up. Refactoring to change all the existing `UserDetails` to `UserDetailOverlay` or `UserDetailCard` and `OwnUser` to `UserDetails` should take one or two hours.

2022-07-28 05:28 UTC, jjeroch commented on cx-portal/src/components/pages/UserManagement/UserDetails/index.tsx
>              userDetailsCards={userDetailsToCards(ownUser)}
Hi both - I dont have a trouble with a ticket, I was just wondering if the trigger is the component or where did basically the name definition started? It would be good to know that since I might need to check this in future earlier to make sure that we see those naming misunderstandings as early as possible. I will put a defect ticket for this in place. We can do this after the release. This is not mission critical

2022-07-28 05:30 UTC, jjeroch approved these changes

2022-07-28 05:33 UTC, nidhigarg-bmw commented on cx-portal/src/components/pages/UserManagement/UserDetails/index.tsx
>              userDetailsCards={userDetailsToCards(ownUser)}
I made the changes of OwnUser to UserDetail into 
https://github.com/catenax-ng/product-portal-frontend/pull/168 branch already.

2022-07-28 05:33 UTC, merged

2022-07-28 05:38 UTC, jjeroch commented on cx-portal/src/components/pages/UserManagement/UserDetails/index.tsx
>              userDetailsCards={userDetailsToCards(ownUser)}
@nidhigarg-bmw is this change resulting into any break? No right? I guess your #168 branch is developed in a way that still those sections which are running on OwnUser are not breaking, right?

2022-07-28 05:49 UTC, nidhigarg-bmw commented on cx-portal/src/components/pages/UserManagement/UserDetails/index.tsx
>              userDetailsCards={userDetailsToCards(ownUser)}
@jjeroch Yeah I checked and nothing is breaking