Feature/cplp 749 admin registration req page
catenax-ng/product-portal-frontend pull request #167
Opened 2022-07-26 20:28 UTC by fatihayyildiz

Admin registration page implemented

2022-07-26 20:37 UTC, jjeroch requested changes

2022-07-26 20:37 UTC, jjeroch commented on cx-portal/src/utils/mockDataSet/registrationRequests.json
> +}
@fatihayyildiz do we really need to keep this data - the plan was to fetch all the relevant data from the API. So I think all mock data can get deleted. Please recheck

2022-07-27 04:46 UTC, lavanya-bmw requested changes
Please add german translation file for main.json as it is missing currently

2022-07-27 09:32 UTC, fatihayyildiz commented
Translation is fixed
mock data deleted

2022-07-27 09:36 UTC, lavanya-bmw submitted a review, later dismissed
Looks good to me

2022-07-27 09:45 UTC, jjeroch submitted a review, later dismissed

2022-07-27 11:09 UTC, oyo requested changes
some small remarks. But one important concept from my POV is to stick to ISO date format instead of some local variant:  `2022-07-27`

2022-07-27 11:09 UTC, oyo commented on cx-portal/src/components/pages/Admin/components/RegistrationRequests/registrationTableColumns.tsx
> +        <span>{dayjs(params?.value).format('DD/MM/YYYY')}</span>
two things here:
- date formatting for localized UIs can get a very complicated issue. Better use the ISO standard for dates that is not only understood globally but also will sort dates in correct order when represented as a string. https://www.iso.org/iso-8601-date-and-time-format.html
- you can use `valueGetter` instead of a rendered cell here: https://mui.com/x/react-data-grid/column-definition/#rendering-cells

So my suggestion is to replace line 33-35 with this:
  `valueGetter: (params: GridRenderCellParams<string>) => dayjs(params?.value).format('YYYY-MM-DD')`

2022-07-27 11:09 UTC, oyo commented on cx-portal/src/components/pages/Admin/components/RegistrationRequests/index.tsx
> +      ...{ size: pageSize, page: 0 },
spread needed?

2022-07-27 11:14 UTC, oyo requested changes

2022-07-27 11:14 UTC, oyo commented on cx-portal/src/components/pages/Admin/components/RegistrationRequests/registrationTableColumns.tsx
>        headerName: `${t('content.admin.registration-requests.columns.date')}`,
not part of this PR but why are all those values wrapped in a backtick template string? this should be enough
`headerName: t('content.admin.registration-requests.columns.date')`

2022-07-28 10:22 UTC, jjeroch commented
@fatihayyildiz  can you please rerun through the comments from Martin

2022-07-29 13:59 UTC, fatihayyildiz commented
@jjeroch all comments fixed/changed. Ready to review and merge

2022-07-29 15:49 UTC, oyo approved these changes
looks good - thank you and good bye Fatih ;)

2022-07-29 15:50 UTC, merged