810,811-app release card
catenax-ng/product-portal-frontend pull request #195
Opened 2022-08-05 01:20 UTC by lavanya-bmw

2022-08-05 09:15 UTC, PI-FerasAhmad submitted a review, later dismissed
looks good to me

2022-08-05 09:47 UTC, oyo requested changes
most comments are just about a more compact way to write things. But don't use material UI directly except `Box` or Icons

2022-08-05 09:47 UTC, oyo commented on cx-portal/src/components/pages/AppReleaseProcess/index.tsx
> +                  <Button color="primary" size="small" className="create-btn" onClick={() => { setCreateApp(true) }}>
no need for curly brackets: `() => setCreateApp(true)`

2022-08-05 09:47 UTC, oyo commented on cx-portal/src/components/pages/AppReleaseProcess/index.tsx
> +                  onClick={() => { setCreateApp(true) }}
no need for the brackets around the function call

2022-08-05 09:47 UTC, oyo commented on cx-portal/src/components/pages/AppReleaseProcess/components/AppMarketCard/index.tsx
> +                        <InputLabel id="Use Case /Category">
please don't use spaces or special characters for id attributes - better `use_case_category`

2022-08-05 09:47 UTC, oyo commented on cx-portal/src/components/pages/AppReleaseProcess/components/AppMarketCard/index.tsx
> +                            onChange={(e) => handleChange(e)}
in all these cases where a function should simply called with the event this is enough:
`onChange={handleChange}`

2022-08-05 09:47 UTC, oyo commented on cx-portal/src/components/pages/AppReleaseProcess/components/AppMarketCard/index.tsx
> +                                    {formData.appTitle === "" ? t('content.apprelease.appMarketCard.defaultCardAppTitle') : formData.appTitle}
for this and all the others it's simpler to write the logic like as
`{formData.appTitle || t('content.apprelease.appMarketCard.defaultCardAppTitle')}`

2022-08-05 09:47 UTC, oyo commented on cx-portal/src/components/pages/AppReleaseProcess/components/AppMarketCard/index.tsx
> +    useEffect(() => {
is there any special reason why you put that in an useEffect hook? I think it should also work without that

2022-08-05 09:47 UTC, oyo commented on cx-portal/src/components/pages/AppReleaseProcess/components/AppMarketCard/index.tsx
> +            window.scrollY === 0 ? setPageScrolled(false) : setPageScrolled(true)
simply write this as
`window.onscroll = () => setPageScrolled(window.scrollY !== 0)`

2022-08-05 09:47 UTC, oyo commented on cx-portal/src/components/pages/AppReleaseProcess/components/AppMarketCard/index.tsx
> +import CardMedia from '@mui/material/CardMedia';
we try to avoid using material UI directly in the cx-portal. Please use the Card component from `cx-portal-shared-components` and extend it if necessary or create missing components there.

2022-08-08 07:16 UTC, oyo approved these changes
looks good now

2022-08-08 07:43 UTC, merged