[CPLP-863] - #1 Search and #2 Data Table Row Height changes done
catenax-ng/product-portal-frontend pull request #228
Opened 2022-08-16 05:34 UTC by smartdeepp

2022-08-16 10:24 UTC, jjeroch requested changes

2022-08-16 10:24 UTC, jjeroch commented on cx-portal-shared-components/src/components/basic/SearchInput/SearchInput.stories.tsx
> +    </IconButton>
We still had the mic in the design element, but planned to not use this for now. I suggest we put this to "inactive" I dont expect it to actually work without extended implementation efforts

2022-08-16 10:24 UTC, jjeroch commented on cx-portal/src/assets/locales/de/main.json
> +      "searchbycompanyorbpnlabel": "",
there is now additionally to the existing tags new tags added. Is there any reason why new tags are added additionally to the exciting tags. Do we still need the existing tags? Likely not, or?

Also I suggest we rename the key to "searchfielddefaulttext"

2022-08-16 10:24 UTC, jjeroch commented on cx-portal/src/assets/locales/en/main.json
> +      "searchbycompanyorbpnplaceholder": "Search by company name or BPN",
same as added in the de/main file comment

2022-08-16 10:24 UTC, jjeroch commented on cx-portal/src/components/pages/PartnerNetwork/components/PartnerNetworkSearchForm.tsx
> +import MicIcon from '@mui/icons-material/Mic'
lets take out the mic

2022-08-16 10:24 UTC, jjeroch commented on cx-portal/src/components/pages/PartnerNetwork/components/PartnerNetworkSearchForm.tsx
> +          }
lets take out the mic

2022-08-16 10:24 UTC, jjeroch commented on cx-portal/src/components/pages/PartnerNetwork/index.tsx
> +        dispatch(getOneBusinessPartner({ bpn: searchText }))
Quick recheck on this one. If the company name is 16 digits long, will we accidentally use the BPN API endpoint?

2022-08-16 10:24 UTC, jjeroch commented on cx-portal-shared-components/src/components/basic/SearchInput/SearchInput.stories.tsx
> +import MicIcon from '@mui/icons-material/Mic'
lets take out the mic, we dont use it for the first release

2022-08-16 10:25 UTC, jjeroch commented
@smartdeepp have added some review comments, can you please update the code. After that will assign to one FE developer for validation

2022-08-16 11:16 UTC, smartdeepp commented on cx-portal-shared-components/src/components/basic/SearchInput/SearchInput.stories.tsx
> +    </IconButton>
ok, removed the mic icon as per the comment

2022-08-16 11:16 UTC, smartdeepp commented on cx-portal/src/assets/locales/de/main.json
> +      "searchbycompanyorbpnlabel": "",
yes, thanks for the suggestion, also made the changes here as per the comment.

2022-08-16 11:19 UTC, smartdeepp commented on cx-portal/src/components/pages/PartnerNetwork/index.tsx
> +        dispatch(getOneBusinessPartner({ bpn: searchText }))
No it didn't, anyways i made some reliable changes to the make the logic bit cleaner to avoid bugs.

2022-08-16 11:21 UTC, smartdeepp commented
@jjeroch i have made the changes as per the comments above.

2022-08-17 08:25 UTC, oyo requested changes
check remarks

2022-08-17 08:25 UTC, oyo commented on cx-portal/src/components/pages/PartnerNetwork/index.tsx
> +  const bpnPattern = /^BPNL[a-z0-9]{12}$/i
We already have patterns defined here - please use those:
https://github.com/catenax-ng/product-portal-frontend/blob/main/cx-portal/src/types/Patterns.ts#L22

2022-08-17 08:25 UTC, oyo commented on cx-portal/src/components/pages/PartnerNetwork/index.tsx
> +const validateSearchText = (text: string): boolean => {
We also have to support some special characters - at least `À-ÿ`
Also I suggest to write this as a one-liner:
`const validateSearchText = (text: string): boolean => /^[a-zÀ-ÿ0-9 !?@&_\-.]*$/i.test(text)`

2022-08-17 08:25 UTC, oyo commented on cx-portal/src/components/pages/PartnerNetwork/index.tsx
> +    let isValidText = validateSearchText(inputElem.value)
use const if the value isn't changed later in the scope. Most of the time there is no need for let

2022-08-17 08:25 UTC, oyo commented on cx-portal/src/components/pages/PartnerNetwork/index.tsx
> +      return setSearchError('Invalid data')
if this error is displayed at the UI at some time we should use translations for it:
`
const { t } = useTranslation()
...
...rror(t('key.to.error.message'))
`

2022-08-17 09:27 UTC, smartdeepp commented on cx-portal-shared-components/src/components/basic/SearchInput/index.tsx
> +  endAndorment?: IconProps
sorry for that mistake, this is taken care of.

2022-08-17 09:27 UTC, smartdeepp commented on cx-portal/src/components/pages/PartnerNetwork/index.tsx
> +  const bpnPattern = /^BPNL[a-z0-9]{12}$/i
thank you for the suggestion, will use that pattern.

2022-08-17 09:28 UTC, smartdeepp commented on cx-portal/src/components/pages/PartnerNetwork/index.tsx
> +    let isValidText = validateSearchText(inputElem.value)
thank you for the suggestion.

2022-08-17 09:28 UTC, smartdeepp commented on cx-portal/src/components/pages/PartnerNetwork/index.tsx
> +      return setSearchError('Invalid data')
did the changes as per your comments, thank you for the feedback.

2022-08-17 09:29 UTC, smartdeepp commented
Hello @oyo , the changes are done as per you requested.

2022-08-17 10:23 UTC, oyo requested changes
another small change - otherwise good

2022-08-17 10:23 UTC, oyo commented on cx-portal/src/components/pages/PartnerNetwork/index.tsx
> +  /^[a-zA-ZÀ-ÿ0-9 !?@&_\-.]*$/.test(text)
oh sorry - one thing I forgot to mention in my last comment. In validations we should never use `*` in regular expressions because we always want to limit the input and we don't start to search for one or two characters and super long input is also not helpful. We can limit the length of a valid input from 3-80 chars with {3,80}. Also the trim is always a good idea. So I now suggest to change the line another time to:
`/^[a-zA-ZÀ-ÿ0-9 !?@&_\-.]{3,80}$/.test(text.trim())`

2022-08-17 10:36 UTC, smartdeepp commented on cx-portal/src/components/pages/PartnerNetwork/index.tsx
> +  /^[a-zA-ZÀ-ÿ0-9 !?@&_\-.]*$/.test(text)
@oyo  can you help me with one last suggestion, if the length is less then 3 do you want me to show that 'Invalid data' error below the input field just as we display when the search text does not satisfy the regex above?

2022-08-17 11:02 UTC, oyo commented on cx-portal/src/components/pages/PartnerNetwork/index.tsx
> +  /^[a-zA-ZÀ-ÿ0-9 !?@&_\-.]*$/.test(text)
@smartdeepp actually the desired behavior is: nothing should happen as long as one or two characters are entered - no message and no search. So maybe you can handle that in line 61 before all other validations do a simple check like this:
`if (inputtext.length<3) return`

2022-08-17 11:07 UTC, smartdeepp commented on cx-portal/src/components/pages/PartnerNetwork/index.tsx
> +  /^[a-zA-ZÀ-ÿ0-9 !?@&_\-.]*$/.test(text)
ok @oyo , thanks for the feedback

2022-08-17 11:14 UTC, smartdeepp commented
@oyo  changes are done, let me know if any changes.

2022-08-17 11:38 UTC, oyo approved these changes
looks good now

2022-08-17 11:40 UTC, oyo commented
@jjeroch for me it looks good now - can you also remove your block once you are happy with the changes?

2022-08-18 22:13 UTC, jjeroch approved these changes

2022-08-18 22:13 UTC, merged