[CPLP-863] partners network cleanup
catenax-ng/product-portal-frontend pull request #248
Opened 2022-08-22 10:49 UTC by smartdeepp

2022-08-23 21:34 UTC, jjeroch commented on cx-portal/public/testdata/partnerNetwork/membershipData.json
> +]
@smartdeepp whats that for?

2022-08-23 21:34 UTC, jjeroch commented on cx-portal/public/testdata/partnerNetwork/businessPartnersDataGrid.json
>          "uuid": "d38cc9b0-e9c8-4a65-a61f-f65fdc89c0d0",
@smartdeepp can you please check if we still need those test data? We dont use them anymore, or are we fetching them for unit tests?

2022-08-24 04:18 UTC, smartdeepp commented on cx-portal/public/testdata/partnerNetwork/businessPartnersDataGrid.json
>          "uuid": "d38cc9b0-e9c8-4a65-a61f-f65fdc89c0d0",
Yes, @jjeroch  , we are using dummy data for unit tests; the same applies to the comment above.

In addition, one of the github actions failed the unit test, so I had to make the necessary modifications.

2022-09-06 06:34 UTC, jjeroch commented
@lavanya-bmw @manojava-gk please review
@smartdeepp there are conflicts. can you please cleanup the conflicts

2022-09-06 06:34 UTC, jjeroch commented on cx-portal/public/testdata/partnerNetwork/businessPartnersDataGrid.json
>          "uuid": "d38cc9b0-e9c8-4a65-a61f-f65fdc89c0d0",
fine

2022-09-06 07:05 UTC, smartdeepp commented
Hello, @lavanya-bmw @manojava-gk, conflicts resolved as per the comment.

2022-09-06 07:28 UTC, lavanya-bmw requested changes
please add your changes to the RELEASENOTES.md file with every PR so we have an overview by the end of the sprint

2022-09-06 09:24 UTC, smartdeepp commented
> please add your changes to the RELEASENOTES.md file with every PR so we have an overview by the end of the sprint

Updated.

2022-09-06 09:31 UTC, lavanya-bmw approved these changes
looks good to me

2022-09-07 05:53 UTC, jjeroch commented
@thackerronak please fix the outstanding release note conflicts

2022-09-07 06:08 UTC, smartdeepp commented
> @thackerronak please fix the outstanding release note conflicts

updated.

2022-09-07 06:11 UTC, lavanya-bmw approved these changes

2022-09-11 17:36 UTC, jjeroch approved these changes

2022-09-11 17:36 UTC, merged