Invite table updated with search functionality. Filter action disabled.
catenax-ng/product-portal-frontend pull request #267
Opened 2022-08-29 12:58 UTC by manojava-gk

2022-08-29 15:06 UTC, oyo approved these changes
everything looks good to me - only wrapping the InviteList in another component doesn't seem right

2022-08-29 15:06 UTC, oyo commented on cx-portal/src/components/pages/InviteBusinessPartner/components/ActiveInviteTable/index.tsx
> +}
looking at this component it is just overhead and doesn't make sense to - better use the InviteList directly instead of ActiveInviteTable

2022-08-29 15:06 UTC, oyo commented on cx-portal/src/components/pages/InviteBusinessPartner/index.tsx
> +        <ActiveInviteTable />
use InviteList here

2022-08-29 15:07 UTC, oyo requested changes
accidentially set to approve - see other comments

2022-08-29 15:16 UTC, lavanya-bmw requested changes
please add a line regarding what is implemented in this PR in RELEASENOTES.md file

2022-08-30 04:51 UTC, manojava-gk commented on cx-portal/src/components/pages/InviteBusinessPartner/components/ActiveInviteTable/index.tsx
> +}
Updated

2022-08-30 05:02 UTC, lavanya-bmw approved these changes
looks good to me

2022-08-30 07:09 UTC, oyo commented
one more thing - please add your changes to the RELEASENOTES.md with every PR so we have an overview by the end of the sprint

2022-08-30 08:48 UTC, oyo approved these changes
looks good to me now

2022-08-30 09:11 UTC, merged