Clpl 1244 own company details
catenax-ng/product-portal-frontend pull request #277
Opened 2022-09-05 06:05 UTC by thackerronak

2022-09-06 07:57 UTC, lavanya-bmw requested changes
- Please fix the code smells
- add header template to the newly created files
- Please add your changes to the RELEASENOTES.md file with every PR so that we can have an overview by the end of the sprint.

2022-09-06 07:57 UTC, lavanya-bmw commented on cx-portal/src/features/admin/mapper.ts
> +    head: 'content.organization.company.name',
translation is missing in this file for head

2022-09-06 07:57 UTC, lavanya-bmw commented on cx-portal/src/components/pages/Organization/index.tsx
> +      ></PageHeader>
PageHeader could be a self closing tag here

2022-09-06 09:04 UTC, thackerronak commented on cx-portal/src/features/admin/mapper.ts
> +    head: 'content.organization.company.name',
yes because this is mapper only, this text get translated while render.

2022-09-06 09:10 UTC, thackerronak commented
> * Please fix the code smells
> * add header template to the newly created files
> * Please add your changes to the RELEASENOTES.md file with every PR so that we can have an overview by the end of the sprint.

done

2022-09-06 09:41 UTC, lavanya-bmw requested changes
Please add header template for mapper.ts and orgainzation.scss too

2022-09-06 09:43 UTC, lavanya-bmw commented on cx-portal/src/features/admin/mapper.ts
> +    head: 'content.organization.company.name',
Oh ok

2022-09-06 10:17 UTC, thackerronak commented
> Please add header template for mapper.ts and orgainzation.scss too

done

2022-09-06 10:34 UTC, lavanya-bmw submitted a review, later dismissed
lgtm

2022-09-07 06:22 UTC, lavanya-bmw approved these changes
lgtm

2022-09-11 17:16 UTC, merged