Recommendation for Unit test run at GH action
catenax-ng/product-portal-frontend pull request #28
Opened 2022-04-19 13:24 UTC by fatihayyildiz

Github action checks workflow created
unit test command moved to checks workflow file

2022-04-19 14:17 UTC, fatihayyildiz commented
@oyo I added new workflow file, runs at PR creation and checking unit tests. Could you please take a look ?

2022-04-19 16:04 UTC, oyo requested changes

2022-04-19 16:04 UTC, oyo commented on .github/workflows/checks.yml
> +        run: yarn build
The full build takes up to 5 minutes with creating that license file and storybook which are not needed for unit tests. I suggest to only build the shared component library at this step by `yarn build:lib`

2022-04-20 11:49 UTC, oyo commented on .github/workflows/checks.yml
> +        run: yarn build
I committed that change and the pipeline is now down to 3 minutes which should be okay

2022-04-20 11:50 UTC, oyo approved these changes
Reduced run time by removing some non-essential steps. Also now only runs when PR is created or updated, not on every PR comment because that feels like too many invocations.

2022-04-21 08:25 UTC, fatihayyildiz commented
Thanks @oyo ,I missed somehow your comments. Looks nice, I think it's ready to merge 👍

2022-04-21 08:25 UTC, merged

2022-04-21 08:27 UTC, oyo commented
> Thanks @oyo ,I missed somehow your comments. Looks nice, I think it's ready to merge 👍

sure - just merge it :)