CPLP1425 & CPLP 1442 Connect partner network to BPDM dev
catenax-ng/product-portal-frontend pull request #290
Opened 2022-09-13 15:28 UTC by manojava-gk

2022-09-15 14:38 UTC, lavanya-bmw submitted a review, later dismissed
looks good to me

2022-09-16 12:16 UTC, oyo requested changes
I missed that on our last call. Under no circumstances should we hard code any content specific code into shared components. The usual way is for the caller to give a function as a prop that would handle the use case specific stuff.

2022-09-16 12:16 UTC, oyo commented on cx-portal-shared-components/src/components/basic/Table/PageLoadingTable.tsx
> +            finalObj = addMemberAttribute(finalObj, additionalHooks.queryData)
we must not hard code any data specific attributes into the shared components

2022-09-16 12:16 UTC, oyo commented on cx-portal-shared-components/src/components/basic/Table/PageLoadingTable.tsx
> +            finalObj.country = payload[0].legalAddress.country
content specific - not in shared components

2022-09-16 12:16 UTC, oyo commented on cx-portal-shared-components/src/components/basic/Table/components/Helper/helper.ts
> +export const addCountryAttribute = (finalObj: any, payload: any) => {
content specific - not in shared components

2022-09-16 12:16 UTC, oyo commented on cx-portal-shared-components/src/components/basic/Table/components/Helper/helper.ts
> +export const addMemberAttribute = (finalObj: any, queryData: any) => {
content specific - not in shared components

2022-09-16 12:55 UTC, oyo commented
please also update release notes

2022-09-19 07:25 UTC, manojava-gk commented
@oyo Have addressed your comments. Let me know your thoughts

2022-09-21 13:15 UTC, oyo approved these changes
lgtm

2022-09-21 13:16 UTC, merged