Feature/cplp 1210/service market place
catenax-ng/product-portal-frontend pull request #292
Opened 2022-09-14 13:47 UTC by nidhigarg-bmw

2022-09-16 12:44 UTC, oyo requested changes
css files should also get copyright headers
it's not a good practice to mix importing .scss and added sx/style={{}} props

2022-09-16 12:44 UTC, oyo commented on cx-portal/src/components/overlays/ServiceRequest/index.tsx
> +        onCloseWithIcon={() => dispatch(show(OVERLAYS.NONE, ''))}
there is a redux action `closeOverlay`

2022-09-16 12:44 UTC, oyo commented on cx-portal/src/components/overlays/ServiceRequest/index.tsx
> +          onClick={() => dispatch(show(OVERLAYS.NONE))}
there is a redux action `closeOverlay`

2022-09-16 12:44 UTC, oyo commented on cx-portal/src/components/pages/ServiceMarketplaceDetail/components/MarketplaceHeader/index.tsx
> +            UserService.hasRole(ROLES.SUBSCRIBE_SERVICE_MARKETPLACE)
better enable/disable this button if the role is not present
`disabled={!UserService.hasRole(ROLES.SUBSCRIBE_SERVICE_MARKETPLACE)}`

or maybe even better: not render the button at all?

2022-09-16 12:44 UTC, oyo commented on cx-portal/src/components/pages/ServiceMarketplaceDetail/components/MarketplaceHeader/index.tsx
> +            UserService.hasRole(ROLES.SUBSCRIBE_SERVICE_MARKETPLACE)
enable/disable - see other comment

2022-09-16 12:44 UTC, oyo commented on cx-portal/src/components/pages/ServiceMarketplaceDetail/components/MarketplaceSubscription/MarketplaceSubscription.scss
> +.marketplace-subscriptions {
header missing

2022-09-16 12:44 UTC, oyo commented on cx-portal/src/components/pages/ServiceMarketplaceDetail/components/MarketplaceProvider/MarketplaceProvider.scss
> +.marketplace-provider {
header missing

2022-09-16 12:44 UTC, oyo commented on cx-portal/src/components/pages/ServiceMarketplaceDetail/components/MarketplaceHeader/MarketplaceHeader.scss
> +.marketplace-header {
header missing

2022-09-16 12:44 UTC, oyo commented on cx-portal/src/components/pages/ServiceMarketplaceDetail/Marketplace.scss
> +.marketplace-main {
header missing

2022-09-16 12:44 UTC, oyo commented on cx-portal/src/components/pages/ServiceMarketplace/style.scss
> +.container {
header missing

2022-09-16 12:44 UTC, oyo commented on cx-portal/src/components/pages/ServiceMarketplace/index.tsx
> +        sx={{
we should not mix importing a `style.scss` and adding a lot of coded style here - go with one solution, but not both of them.

2022-09-16 12:44 UTC, oyo commented on cx-portal/src/components/pages/ServiceMarketplaceDetail/components/MarketplaceSubscription/MarketplaceSubscriptionNames.tsx
> +      {'#' + index}
I think you can add this number with pure css by customizing an `<ol>` element

2022-09-16 12:44 UTC, oyo commented on cx-portal/src/components/pages/ServiceMarketplaceDetail/index.tsx
> +        sx={{ margin: '50px 0px 0px 90px' }}
again mix of imported and custom style

2022-09-16 12:55 UTC, oyo commented
please also update release notes

2022-09-19 07:13 UTC, nidhigarg-bmw commented
@oyo I have fixed all the request changes. Can you please review again.

2022-09-19 07:22 UTC, oyo submitted a review, later dismissed
looks good now :)

2022-09-19 07:30 UTC, oyo approved these changes
now good - resolved merge conflicts for release notes

2022-09-19 07:46 UTC, merged