App page-business logic
catenax-ng/product-portal-frontend pull request #295
Opened 2022-09-16 08:56 UTC by lavanya-bmw

2022-09-16 12:53 UTC, oyo requested changes
some minor remarks

2022-09-16 12:53 UTC, oyo commented on cx-portal/src/components/pages/AppReleaseProcess/components/AppPage/index.tsx
> +                      value: /^([A-Za-z.:@0-9&_ -]){10,2000}$/,
it was already there before but we have the `types/Patterns.ts` where we should manage all used Regex patterns in the application.

2022-09-16 12:53 UTC, oyo commented on cx-portal/src/components/pages/AppReleaseProcess/components/AppPage/index.tsx
> +                      value: /^([A-Za-z.:@0-9&_ -]){10,2000}$/,
also there before but please use a const for the max length like `const MAX_INPUT_LENGTH = 2000` so we have only one place where to change this

2022-09-16 12:53 UTC, oyo commented on cx-portal/src/components/pages/AppReleaseProcess/components/AppPage/index.tsx
> +                  value: Patterns.PHONE,
good

2022-09-16 12:53 UTC, oyo commented on cx-portal/src/components/pages/AppReleaseProcess/components/ValidateAndPublish/index.tsx
>    }
are the curly brackets required here?

2022-09-16 12:53 UTC, oyo commented on cx-portal/src/features/appManagement/slice.ts
> +export const appIdSelector = (state: RootState): any => state.management.appId
replace this `any` with the return type: `string`

2022-09-16 12:56 UTC, oyo commented
please also update release notes

2022-09-16 15:35 UTC, lavanya-bmw commented
> please also update release notes

this is already updated

2022-09-19 07:24 UTC, oyo approved these changes
looks good now

2022-09-19 07:26 UTC, merged