Added step-1 validation for description fields and document changes
catenax-ng/product-portal-frontend pull request #355
Opened 2022-10-06 05:55 UTC by lavanya-bmw

2022-10-06 13:47 UTC, oyo requested changes

2022-10-07 03:23 UTC, lavanya-bmw commented on cx-portal/src/features/appManagement/slice.ts
> +      state.currentActiveStep = 1
@oyo After completing all steps and submitting the app release process successfully and if user again goes to app release process, the user should be able to see step1 again. (This is not related to the ticket 1624, but a small adjustment added to this PR)

2022-10-07 03:27 UTC, lavanya-bmw commented on cx-portal/src/components/pages/AppReleaseProcess/components/AppMarketCard/index.tsx
> +                                : 'A-Za-z0-9.: @&_-,äüö'
@jjeroch Can you please check and confirm me if these characters also to be included in the validations?

2022-10-07 07:33 UTC, jjeroch commented on cx-portal/src/components/pages/AppReleaseProcess/components/AppMarketCard/index.tsx
> +                                : 'A-Za-z0-9.: @&_-,äüö'
Is this the short description? If so, I would not open up the characters that much. Its only one sentence, so we should keep it limited to some key characters. I did do a mix from the actual validation and the proposal from martin - ideally we do following for the short description:
`a-zA-ZÀ-ÿ0-9 !?@&#'"()_-=/*.,;:`

and lets use the full list `a-zA-ZÀ-ÿ0-9 !?@&#'"()[]_-+=<>/*.,;:` for the long description field (y)

2022-10-07 07:34 UTC, jjeroch commented on cx-portal/src/types/Patterns.ts
> +    shortDescriptionDE: /^([A-Za-z.:@0-9&_ ,äüö-]){10,255}$/,
see comment above :) thanks for the suggestion

2022-10-11 07:21 UTC, manojava-gk submitted a review, later dismissed
lftm

2022-10-12 10:29 UTC, oyo approved these changes
looks good now

2022-10-12 10:31 UTC, merged