Show Application details overlay on clicking card when it is in review state
catenax-ng/product-portal-frontend pull request #373
Opened 2022-10-12 11:36 UTC by manojava-gk

2022-10-12 19:35 UTC, jjeroch requested changes

2022-10-12 19:35 UTC, jjeroch commented on RELEASENOTES.md
> +* Feature - App overviw - Show details overlay when Application status is in "in review"
@manojava-gk  can you please adjust the spelling mistake. Usually not worth a comment, but since this is getting stored and officially released, we should make sure that we do not have spelling mistakes. I suggest the following "Feature - App Overview: App detail overlay added for apps in status "in review""

2022-10-12 19:35 UTC, jjeroch commented on cx-portal/src/components/pages/AppOverview/AppOverViewDetails.tsx
> +                src: 'https://catenaxdev003util.blob.core.windows.net/assets/apps/images/Lead-Default.png',
@manojava-gk can you just recheck this. The dev003 is an old env. which is about to get retired. What are we fetching here from dev003?

2022-10-12 19:35 UTC, jjeroch commented on cx-portal/src/components/overlays/AppOverViewConfirm/AppDetailsOverlay.tsx
> +import { useFetchAppDetailsQuery } from 'features/apps/apiSlice'
@manojava-gk we should switch to the following api endpoint: GET: /api/apps/appreleaseprocess/{appId}/appStatus 
the endpoint is the app-release-app-detail-endpoint used inside the app release process by Lavanya as well. Ideally you can reuse and possibly enhance the usage of the endpoint. But I suggest to recheck with Lavanya to ensure that we limit double efforts

2022-10-13 04:40 UTC, manojava-gk commented on cx-portal/src/components/pages/AppOverview/AppOverViewDetails.tsx
> +                src: 'https://catenaxdev003util.blob.core.windows.net/assets/apps/images/Lead-Default.png',
This is just a default image. Some other file was using it as catena grey logo. Will update it

2022-10-13 04:41 UTC, manojava-gk commented on cx-portal/src/components/overlays/AppOverViewConfirm/AppDetailsOverlay.tsx
> +import { useFetchAppDetailsQuery } from 'features/apps/apiSlice'
I spoke to Lavanya. She is working on that api. Will update once it is merged to dev

2022-10-13 11:51 UTC, oyo requested changes
one change with the closeOverlay

2022-10-13 11:51 UTC, oyo commented on cx-portal/src/components/overlays/AppOverViewConfirm/AppDetailsOverlay.tsx
> +          onCloseWithIcon: () => dispatch(show(OVERLAYS.NONE, '')),
we have an action called `closeOverlay()` that we should use instead of `show(OVERLAYS.NONE, '')`

2022-10-14 07:57 UTC, oyo submitted a review, later dismissed
lgtm

2022-10-14 08:13 UTC, lavanya-bmw approved these changes
lgtm

2022-10-14 09:06 UTC, jjeroch commented on cx-portal/src/components/overlays/AppOverViewConfirm/AppDetailsOverlay.tsx
> +import { useFetchAppDetailsQuery } from 'features/apps/apiSlice'
@manojava-gk  will merge the pr today. Update/change to the new api should be done in a new branch/pr

2022-10-14 09:06 UTC, jjeroch approved these changes

2022-10-14 09:06 UTC, merged