Filter and Load more button issue
catenax-ng/product-portal-frontend pull request #374
Opened 2022-10-12 13:11 UTC by manojava-gk

2022-10-12 19:20 UTC, jjeroch requested changes

2022-10-13 04:59 UTC, manojava-gk commented on RELEASENOTES.md
> +* Bugfix - Filter & load more issue fix
This is done

2022-10-14 08:14 UTC, lavanya-bmw approved these changes
lgtm

2022-10-14 09:08 UTC, jjeroch approved these changes

2022-10-14 09:08 UTC, merged