User action confirm, success and error overlays
catenax-ng/product-portal-frontend pull request #398
Opened 2022-10-21 04:39 UTC by manojava-gk

CPLP 847, 848, 849, 850

2022-10-21 13:29 UTC, oyo requested changes
some small changes

2022-10-21 13:29 UTC, oyo commented on cx-portal/src/components/overlays/AddTechnicalUser/TechnicalUserAddResponseOverlay.tsx
> +  iconComponent?: any
these should not be `any` - can we be more specific, something like 
`handleCallback?: () => void`
`iconComponent?: JSX.Element`

2022-10-21 13:29 UTC, oyo commented on cx-portal/src/components/overlays/AddTechnicalUser/TechnicalUserAddResponseOverlay.tsx
> +            if (handleCallback) handleCallback()
if () not needed when the type is not `any`

2022-10-21 13:29 UTC, oyo commented on cx-portal/src/components/overlays/ConfirmUserAction/index.tsx
> +  }
I think you can write this function as one expression:
`const canHideOverlay = () => !!response === !!error`
the `!!` will convert both to a boolean and then it will be `true` when both are the same value (true or false) and `false` when one of them is true and the other one false.

2022-10-27 05:45 UTC, manojava-gk commented on cx-portal/src/components/overlays/AddTechnicalUser/TechnicalUserAddResponseOverlay.tsx
> +            if (handleCallback) handleCallback()
if () statement is to avoid undefined error right?

this error is showing up in VS code if () statement is removed
Cannot invoke an object which is possibly 'undefined'.

2022-10-27 08:54 UTC, oyo approved these changes
looks good to me now

2022-10-27 14:26 UTC, jjeroch approved these changes

2022-10-27 14:45 UTC, merged