search functionality in app marketplace and bpn adress ui fixed
catenax-ng/product-portal-frontend pull request #404
Opened 2022-10-26 11:37 UTC by nidhigarg-bmw

2022-10-26 12:57 UTC, oyo requested changes
one small remark

2022-10-26 12:57 UTC, oyo commented on cx-portal/src/components/pages/AppMarketplace/components/AppListSection/index.tsx
> +      }, 300),
how about this more compact implementation?
`
debounce((expr: string) => setCardsData(
  expr
    ? cards.filter(...etc...)
    : cards
), 300)
`

2022-10-28 06:54 UTC, nidhigarg-bmw commented on cx-portal/src/components/pages/AppMarketplace/components/AppListSection/index.tsx
> +      }, 300),
@oyo  Done this change, please review again

2022-10-28 07:11 UTC, oyo approved these changes
lgtm now

2022-10-28 07:21 UTC, merged