Register connector  model update
catenax-ng/product-portal-frontend pull request #406
Opened 2022-10-27 14:40 UTC by manojava-gk

2022-10-28 06:59 UTC, oyo requested changes
There is a type definition missing for Connector. If we start using `any` everywhere our code becomes more likely to run into bugs.

2022-10-28 06:59 UTC, oyo commented on cx-portal/src/components/pages/EdcConnector/AddConnectorOverlay/components/ConnectorTypeSelection.tsx
> +  selectedServiceCallback: (selected: any) => any
we need to define a Type for the Connector and use that one everywhere instead of `any`

2022-10-28 07:12 UTC, manojava-gk commented on cx-portal/src/components/pages/EdcConnector/AddConnectorOverlay/components/ConnectorTypeSelection.tsx
> +  selectedServiceCallback: (selected: any) => any
I have already addressed this issue. Will push these changes in a while

2022-10-28 11:37 UTC, oyo commented on cx-portal/src/components/pages/EdcConnector/AddConnectorOverlay/components/ConnectorTypeSelection.tsx
> +  selectedServiceCallback: (selected: any) => any
you mean in this PR or in a separate one?

2022-10-28 13:41 UTC, oyo approved these changes
lgtm now
Edit: noticed some more things below

2022-10-28 13:44 UTC, oyo requested changes
one more thing I noticed - patterns

2022-10-28 13:44 UTC, oyo commented on cx-portal/src/components/pages/EdcConnector/AddConnectorOverlay/components/ConnectorInsertForm.tsx
> +                      pattern: /^(BPNL)[0-9A-Z]{12}$/i,
please use the global `Patterns.BPN` type for common input patterns
https://github.com/catenax-ng/product-portal-frontend/blob/main/cx-portal/src/types/Patterns.ts#L22
(maybe also change other patterns in that file)

2022-10-28 13:48 UTC, oyo requested changes

2022-10-28 13:48 UTC, oyo commented on cx-portal/src/components/pages/EdcConnector/AddConnectorOverlay/components/ConnectorInsertForm.tsx
> +            {selectedService && selectedService.type === 'MANAGED_CONNECTOR' && (
Here it's also better to define an enum for number or string constants and use this for comparisons. This way we have better support from the IDE and avoid errors for example when there is a typo in the string or wenn the value changes in the future:
`
enum ConnectorType {
  MANAGED_CONNECTOR = 'MANAGED_CONNECTOR', 
  ...
}
`

2022-11-02 07:10 UTC, manojava-gk commented on cx-portal/src/components/pages/EdcConnector/AddConnectorOverlay/components/ConnectorTypeSelection.tsx
> +  selectedServiceCallback: (selected: any) => any
Yes. Will update in this PR itself. I had started next task which is dependent on this in the same branch.

2022-11-02 07:12 UTC, manojava-gk commented on cx-portal/src/components/pages/EdcConnector/AddConnectorOverlay/components/ConnectorInsertForm.tsx
> +                      pattern: /^(BPNL)[0-9A-Z]{12}$/i,
Did your changes merged to dev? I was waiting for the https pattern as well

2022-11-02 10:00 UTC, oyo commented on cx-portal/src/components/pages/EdcConnector/AddConnectorOverlay/components/ConnectorInsertForm.tsx
> +                      pattern: /^(BPNL)[0-9A-Z]{12}$/i,
oh right - my PR with the Regex patterns hasn't been approved so far:
https://github.com/catenax-ng/product-portal-frontend/pull/396 
could you maybe have a look at it? then you could re-use the URL pattern or the `isURL()` method

2022-11-02 17:10 UTC, manojava-gk commented on cx-portal/src/components/pages/EdcConnector/AddConnectorOverlay/components/ConnectorInsertForm.tsx
> +                      pattern: /^(BPNL)[0-9A-Z]{12}$/i,
Ok. Will update those changes

2022-11-03 09:02 UTC, oyo requested changes
see two more comments about the code smells

2022-11-03 09:02 UTC, oyo commented on cx-portal/src/types/Patterns.ts
> +    NAME: /^[a-zA-Z0-9 @)]{2,20}$/i,
there are a lot of code smells because of unnecessary characters. this is because the pattern ends with `/...../i` that means it is case insensitive. In this case we don't need to specify `[a-zA-Z]` - only one of them like `[a-z]` is enough to cover upper and lower case

2022-11-03 09:35 UTC, oyo commented
also plz resolve merge conflicts

2022-11-03 10:59 UTC, manojava-gk commented on cx-portal/src/types/Patterns.ts
> +    NAME: /^[a-zA-Z0-9 @)]{2,20}$/i,
I have removed this. I'm using your method for the validation

2022-11-04 05:56 UTC, manojava-gk commented on cx-portal/src/types/Patterns.ts
> +    COUNTRY: /^[A-Z)]{2}$/i,
Removed URL pattern and updated NAME expression

2022-11-07 11:40 UTC, oyo submitted a review, later dismissed
looks good to me now

2022-11-07 12:16 UTC, nidhigarg-bmw approved these changes
okay now

2022-11-07 12:16 UTC, merged