fixed status issue
catenax-ng/product-portal-frontend pull request #408
Opened 2022-10-31 12:35 UTC by nidhigarg-bmw

2022-11-01 06:47 UTC, lavanya-bmw requested changes
Please fix the code smell

2022-11-02 10:14 UTC, oyo requested changes

2022-11-02 10:14 UTC, oyo commented on cx-portal/src/components/shared/frame/UserList/index.tsx
>                  <StatusTag color="label" label={t(`global.field.${label}`)} />
better simply go with
`t('global.field.${status}')`
and put in the status value

2022-11-02 10:14 UTC, oyo commented on cx-portal/src/components/shared/frame/UserList/index.tsx
> +  const getStatusLabel = (status: string) => {
it's not good that status is a string. If we know all possible values we should define an enum type like
`enum UserStatus { ACTIVE = 'ACTIVE', INACTIVE = 'INACTIVE', ... etc }`
in this case we also don't need that entire function because we can simply read that  values directly from the i18n files.

2022-11-02 10:14 UTC, oyo commented on cx-portal/src/assets/locales/de/main.json
> +      "active": "AKTIV",
just set those values to upper case:
`"ACTIVE": "Aktiv", ` etc...

2022-11-02 10:24 UTC, nidhigarg-bmw commented on cx-portal/src/components/shared/frame/UserList/index.tsx
>                  <StatusTag color="label" label={t(`global.field.${label}`)} />
@oyo status is coming in caps like ACTIVE, INACTIVE  so shall I placed these value directly in translation ?

2022-11-02 13:04 UTC, oyo submitted a review, later dismissed
looks good now

2022-11-02 14:03 UTC, oyo approved these changes
lgtm

2022-11-03 05:10 UTC, lavanya-bmw approved these changes
lgtm

2022-11-03 05:20 UTC, merged