Feature/cplp 724/idp cleanup
catenax-ng/product-portal-frontend pull request #434
Opened 2022-11-13 21:51 UTC by oyo

2022-11-14 05:52 UTC, jjeroch commented
@oyo  hier noch zur info das displayName pattern das im api gesetzt ist

- Display Name should have minimum 2 digits and maximum 30 digits

Allowed are:
- a-zA-Z0-9
- !?@&#'"()_-=/*.,;:
- {space}

2022-11-14 08:56 UTC, jjeroch commented
> > @oyo hier noch zur info das displayName pattern das im api gesetzt ist
> > 
> > * Display Name should have minimum 2 digits and maximum 30 digits
> > 
> > Allowed are:
> > 
> > * a-zA-Z0-9
> > * !?@&#'"()_-=/*.,;:
> > * {space}
> 
> @jjeroch - im Ernst... damit sind ja nicht mal Umlaute möglich? Okay, sehe gerade im Partner Network gibts offenbar auch keine Umlaute. Die werden dann wohl grundsätzlich durch ae, oe, etc. ersetzt.

@oyo  im ernst das hier: `/^[a-z0-9À-ÿ][a-z0-9À-ÿ-_+-=.,:;!?'"/&@#() ]{1,30}$/i`
Änderung: Länge und noch 2-3 Zeichen mit aufgenommen. Testest du es nochmal mit deinem Testtool gegen bitte

2022-11-17 11:21 UTC, lavanya-bmw requested changes
Please add german translations file too as it is missing and please fix the conflicts

2022-11-17 11:36 UTC, lavanya-bmw requested changes

2022-11-17 11:36 UTC, lavanya-bmw commented on cx-portal/src/components/pages/IDPManagement/IDPList.tsx
> -import { CardHorizontalTable, DataProp } from 'cx-portal-shared-components'
Please add header template, it is currently removed

2022-11-17 11:36 UTC, lavanya-bmw commented on cx-portal/src/components/pages/IDPDetail/IDPDetailContent.tsx
> +        <Typography variant="h4">{'Identity Provider Details'}</Typography>
Please add the header('Identity Provider Details') from translations

2022-11-17 11:38 UTC, nidhigarg-bmw commented on cx-portal/src/components/overlays/DeleteIDP/index.tsx
> +      console.log(response)
remove logs

2022-11-17 11:38 UTC, nidhigarg-bmw commented on cx-portal/src/components/overlays/EnableIDP/index.tsx
> +    console.log(idpEnableData)
remove logs

2022-11-17 11:38 UTC, nidhigarg-bmw commented on cx-portal/src/components/pages/IDPManagement/IDPList.tsx
> -import { CardHorizontalTable, DataProp } from 'cx-portal-shared-components'
Add headers

2022-11-17 11:38 UTC, nidhigarg-bmw commented on cx-portal/src/components/pages/Test/index.dropzone.tsx
> +    console.log(files)
remove logs

2022-11-24 13:11 UTC, lavanya-bmw submitted a review, later dismissed
lgtm

2022-11-24 13:17 UTC, nidhigarg-bmw submitted a review, later dismissed

2022-11-24 13:35 UTC, jjeroch commented
@nidhigarg-bmw & @lavanya-bmw the changelog.md has a "in progress" area again as far as I save. I kicked this out several times now but it always gets re-added. Can you please clean that up still please

2022-11-24 13:36 UTC, jjeroch requested changes

2022-11-24 13:36 UTC, jjeroch commented on cx-portal/src/types/Patterns.ts
> +  COMPANY_NAME: /^[a-z0-9À-ÿ][a-z0-9À-ÿ-_+=.,:;!?'"/&@() ]{1,40}$/i,
2 issues - we want to have only 30 digits and it doesnt support only one space not several spaces behind each other @nidhigarg-bmw any chance to get this fixed?

2022-11-27 18:23 UTC, jjeroch approved these changes

2022-11-27 21:02 UTC, merged