Cplp 818/app card
catenax-ng/product-portal-frontend pull request #436
Opened 2022-11-14 05:23 UTC by lavanya-bmw

2022-11-14 05:48 UTC, jjeroch commented
@lavanya-bmw you are likely already on it - there was a bug identified: https://sonarcloud.io/project/issues?id=catenax-ng_product-portal-frontend&pullRequest=436&resolved=false&types=BUG

2022-11-14 07:36 UTC, oyo requested changes
React requires the `key` attribute for items in a loop. you can use an ID or simply use the map index value.
`items.map((item, i) => <element key={i} ... `

2022-11-14 07:36 UTC, oyo commented on cx-portal/src/components/pages/AppReleaseProcess/components/ValidateAndPublish/index.tsx
> +            {['language', 'useCase', 'price'].map((item: any) => (
item is of type `string` here - avoid any whenever possible. In this simple case it is also okay to just go without the type.
Also when we do a loop the next JSX item in the line below should have a key attribute
`<div key={item} ....`

2022-11-14 07:36 UTC, oyo commented on cx-portal/src/components/pages/AppReleaseProcess/components/ValidateAndPublish/index.tsx
> +          <div>
same as above - div needs a key here

2022-11-14 07:36 UTC, oyo commented on cx-portal/src/components/pages/AppReleaseProcess/components/ValidateAndPublish/index.tsx
> +            <Box sx={{ margin: '37px auto 0 auto' }}>
missing key after map

2022-11-14 07:36 UTC, oyo commented on cx-portal/src/components/pages/AppReleaseProcess/components/ValidateAndPublish/index.tsx
> +          {defaultValues.consent?.map((item: any, index: number) => (
missing key after map - type instead of any

2022-11-14 07:36 UTC, oyo commented on cx-portal/src/components/pages/AppReleaseProcess/components/ValidateAndPublish/index.tsx
> +          .map((i: any) => i && i[0]?.documentName)
specify type instead of any. this part is not easy to read - why do we need the two `.map` loops in a row?

2022-11-14 07:36 UTC, oyo commented on cx-portal/src/components/pages/AppReleaseProcess/components/ValidateAndPublish/index.tsx
> +          {defaultValues.cxTestRuns?.map((item: any, index: number) => (
missing key & type

2022-11-14 07:36 UTC, oyo commented on cx-portal/src/components/shared/basic/Dropzone/index.tsx
> +        <Typography
missing key in Typography

2022-11-16 18:17 UTC, jjeroch requested changes

2022-11-16 18:17 UTC, jjeroch commented on cx-portal-shared-components/src/components/basic/ToolTips/index.tsx
> +      padding: 25,
@lavanya-bmw why did we put the padding to 25? Is there a specific reason?

2022-11-16 18:17 UTC, jjeroch commented on cx-portal/src/assets/locales/en/main.json
> -        "appCardDetails": "App Card Details"
@lavanya-bmw do you know why we deleted this?

2022-11-16 18:17 UTC, jjeroch commented on cx-portal/src/services/EnvironmentService.test.ts
> +    idp: 'https://centralidp.demo.catena-x.net/auth',
@lavanya-bmw you recheck this change please. As per my understanding we need the int.demo.
Feel free to also contact Evelyn to recheck the right setting

2022-11-16 18:17 UTC, jjeroch commented on cx-portal/src/services/EnvironmentService.ts
> +    return 'https://centralidp.demo.catena-x.net/auth'
same as above - to be checked if int.demo should be kept. I would expect so

2022-11-17 07:47 UTC, closed without merging