Feature/cplp 720/app detail page
catenax-ng/product-portal-frontend pull request #44
Opened 2022-05-02 10:40 UTC by nidhigarg-bmw

2022-05-03 13:46 UTC, oyo requested changes
see some comments

2022-05-03 13:46 UTC, oyo commented on cx-portal/public/testdata/appDetails.json
> +{
this is not used any more and can be deleted - the test data is now in a different repo
https://github.com/catenax-ng/product-portal-common-assets/blob/main/public/assets/api/apps/demo/details.json
and available at URL:
https://portal-dev.demo.catena-x.net/assets/api/apps/demo/details.json

2022-05-03 13:46 UTC, oyo commented on cx-portal/src/components/pages/AppDetail/components/AppDetailHeader/index.tsx
> +          <h2 className="heading">{item.name}</h2>
This was from my original example where I didn't care much about the look. In the final component we should use our shared `<Typography />` for all `<p>` or `<h*>` tags

2022-05-03 13:46 UTC, oyo commented on cx-portal/src/components/pages/AppDetail/components/AppDetailHeader/index.tsx
> +            <b>{t('content.appdetail.usecase')}:</b>{' '}
please don't use `<b>` tags. This is styling and should be handled in the (s)css

2022-05-03 13:46 UTC, oyo commented on cx-portal/src/components/pages/AppDetail/index.tsx
> +            World of Grammar...
this is the app long description and should be replaced with

`{ta('${item.id}.description')}`

where ta is defined at the function entry 

`const { ta } = useTranslation('apps')`

we will later provide the translations for those texts either through an api or a generated static JSON file. Doing that will require to create a little shared component `ReadMoreText` that will check and truncate the text if too long. There are many components for that - this looks easy to use: https://www.npmjs.com/package/react-show-more

2022-05-09 09:19 UTC, oyo approved these changes
looks good to me now :)

2022-05-09 09:21 UTC, oyo commented
@jjeroch removed the rating now

2022-05-09 09:54 UTC, jjeroch commented
> @jjeroch removed the rating now

Thanks Martin & Nidhi

2022-05-09 09:55 UTC, jjeroch approved these changes

2022-05-09 10:47 UTC, merged