Feature/cplp 13 user management header
catenax-ng/product-portal-frontend pull request #47
Opened 2022-05-03 07:25 UTC by PI-FerasAhmad

User management component
- click on an app will route to new page _usermanagement/app-user-details/{appId}_
- business logic not yet implemented
- new subHeader Component can be used to in another's pages

2022-05-03 10:48 UTC, PI-FerasAhmad commented
@oyo @floriansommerraysono 
- Back Button added
- Router name changes

2022-05-03 12:46 UTC, floriansommerraysono commented on cx-portal/src/components/pages/UserManagement/AppUserDetails/index.tsx
> +import { AppUserDetailsTable } from './components/AppUserDetalisTable'
Typo in Component?

2022-05-03 12:54 UTC, oyo requested changes

2022-05-03 12:54 UTC, oyo commented on cx-portal/src/components/pages/UserManagement/AppUserDetails/components/AppUserDetalisTable/index.tsx
> +import {
folder name typo

2022-05-03 12:54 UTC, oyo commented on cx-portal/src/components/shared/frame/SubHeader/index.tsx
> +          viewBox="0 0 1440 60"
this hard coded width seems problematic with higher resolution screens. Is it possible to implement this svg as a data url in a css background image that is repeatable in x direction?

2022-05-03 12:54 UTC, oyo commented on cx-portal/src/components/shared/frame/SubHeader/index.tsx
> +        </Typography>
see my ticket https://jira.catena-x.net/browse/CPLP-904 - maybe we should start this soon before we have copied the ugly code too often. Here <SubHeaderTitle ...>

2022-05-03 12:54 UTC, oyo commented on cx-portal/src/components/shared/frame/SubHeader/SubHeader.scss
> +  margin: 20px auto 0px auto;
that duplicate margin setting made Sonarcloud complain

2022-05-03 12:54 UTC, oyo commented on cx-portal/src/components/pages/UserManagement/AppUserDetails/components/AppUserDetalisTable/index.tsx
> +        </Typography>
see my ticket https://jira.catena-x.net/browse/CPLP-904

2022-05-04 06:25 UTC, PI-FerasAhmad commented on cx-portal/src/components/shared/frame/SubHeader/index.tsx
> +        </Typography>
OK, I will create new component to reuse it instead of writing all of Typography code.

2022-05-04 06:49 UTC, PI-FerasAhmad commented on cx-portal/src/components/shared/frame/SubHeader/SubHeader.scss
> +  margin: 20px auto 0px auto;
right, will be removed.

2022-05-05 07:10 UTC, floriansommerraysono approved these changes

2022-05-05 08:16 UTC, oyo approved these changes
unable to reduce the duplications under that limit - we can merge anyway :)

2022-05-05 08:23 UTC, PI-FerasAhmad commented
@oyo many thanks. I will merge this PR.

2022-05-05 08:25 UTC, merged