Feature/SLDT - adds digital twin feature
catenax-ng/product-portal-frontend pull request #53
Opened 2022-05-06 06:36 UTC by JaneMcBrain

Implements the following designs:
Twin overview: https://www.figma.com/file/pcHZWXTQJUguIT75QSk9KW/Portal-Designs?node-id=1010%3A86762
Twin detail: https://www.figma.com/file/pcHZWXTQJUguIT75QSk9KW/Portal-Designs?node-id=851%3A75024
Includes also a first Accordion component.

Jira ticket: https://jira.catena-x.net/browse/A1SLDT-476

2022-05-06 06:41 UTC, JaneMcBrain commented on cx-portal/src/components/pages/DigitalTwins/Header.tsx
> +const Header =() => {
@oyo I was wondering, why we are not having a component for this already? Because I just reused it from somewhere else. Registration Request and Network Partner is using the same code...

2022-05-09 15:44 UTC, oyo requested changes
nicely integrated but some minor points from my side mostly regarding the accordion and the env vars. maybe we can sync this week to talk about that.

2022-05-09 15:44 UTC, oyo commented on cx-portal/.env
> +REACT_APP_SLDT_API_BASE_URL=https://catenaxintakssrv.germanywestcentral.cloudapp.azure.com/semantics
we just got rid of the .env file because this leads to images that are env dependent. Have a look at the new EnvironmentService that is supposed to return the Service URL depending on the document location. Some are still set to a fixed URL:
https://github.com/catenax-ng/product-portal-frontend/blob/main/cx-portal/src/services/EnvironmentService.ts#L26-L32
you could copy that `getBpdmApiBase()` function

2022-05-09 15:44 UTC, oyo commented on cx-portal/src/state/features/digitalTwins/api.ts
> +    super(`${process.env.REACT_APP_SLDT_API_BASE_URL}/twin-registry/registry/shell-descriptors`)
see my comment at the .env file. I suggest to replace this env var with `getSldtApiBase()`

2022-05-09 15:44 UTC, oyo commented on cx-portal-shared-components/src/components/basic/CustomAccordion/CustomAccordion.stories.tsx
> +}
I found it hard to follow how the accordion works in the storybook - can we somehow show an example with multiple accordions?

2022-05-10 06:10 UTC, JaneMcBrain commented on cx-portal-shared-components/src/components/basic/CustomAccordion/CustomAccordion.stories.tsx
> +}
yes, at the moment I didn't implement it properly... will fix it.

2022-05-10 09:14 UTC, JaneMcBrain commented on .husky/pre-commit
> +# npm run lint --fix
When running yarn pretty I get 84 file changes - I am not sure, if this is intended - can I run yarn pretty for specific files instead?

2022-05-12 07:26 UTC, oyo commented
@JaneMcBrain looks quite good now - do you also want to have a look at those two code smells from the Sonarcloud scan? I guess both should be easy to fix.

2022-05-12 10:34 UTC, oyo approved these changes
passt

2022-05-13 09:49 UTC, merged